### ISSUE TITLE
AzureRedisEvents is not published when simulating failover (via Reboot)

### ISSUE THREAD

**Issue by arabelaa** [Azure/AzureCacheForRedis#7]
I followed the steps provided https://github.com/Azure/AzureCacheForRedis/blob/main/AzureRedisEvents.md and subscribed to `AzureRedisEvents` channel to better handle failover events.

I simulated a planned failover event via Reboot option (as mentioned https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-cache-for-redis/cache-failover.md#explanation-of-a-failover) but no event was published on the mentioned channel. 

Is there a way to simulate a planned maintenance event? 
Is the event published only for premium tier?

It would be extremely helpful to have a way to validate/test that `AzureRedisEvents` are published in case of failover/maintenance events.

**Comment by philon-msft** [comment]
Hi @arabelaa, rebooting nodes should publish a notification on all cache SKUs. Is your client app able to receive other pub/sub messages?

**Comment by arabelaa** [comment]
It seems I am not able to receive any published messages. Which is strange because in console when `psusbscribe AzureRedisEvents` I am able to see the events when Reboot happens. I am using `StackExchange.Redis` and` Primary connection string (StackExchange.Redis)` to subscribe to events. 

The client can connect to Azure Cache for Redis but when subscribing to `AzureRedisChannel` no events are coming in.
Not sure what might be the issue. Do I need a special port to be opened?

**Comment by philon-msft** [comment]
@arabelaa, good to hear that it's working for you now. Thanks for posting the solution!
